export const artists = [
  {
    slug: 'king-yardie',
    name: 'King Yardie',
    genre: 'Dancehall',
    subGenre: 'Afro-Dancehall',
    origin: 'Kingston, Jamaica',
    bio: "King Yardie is the flagship artist of YardStyle Entertainment, known for his commanding stage presence and hard-hitting dancehall anthems. With a voice that commands respect and lyrics that resonate across the diaspora, he has become a defining force in modern dancehall culture.",
    longBio: "Born in the heart of Kingston's Arnett Gardens community, King Yardie grew up surrounded by the sound system culture that would define his artistic identity. His debut album 'Crown Pon Mi Head' catapulted him into the spotlight, earning him collaborations with artists across the Caribbean, UK, and North America. His music blends the raw energy of traditional dancehall with contemporary production, creating a sound that bridges generations.",
    image: null,
    color: '#d4af37',
    stats: { streams: '12M+', shows: '200+', albums: 3, awards: 8 },
    socials: { instagram: '#', twitter: '#', youtube: '#', spotify: '#' },
    tracks: [
      { title: 'Crown Pon Mi Head', duration: '3:42', plays: '2.1M', album: 'Crown Pon Mi Head' },
      { title: 'Yardie Anthem', duration: '4:01', plays: '1.8M', album: 'Yard Vibes Vol.1' },
      { title: 'Rise & Shine', duration: '3:28', plays: '1.4M', album: 'Elevation' },
      { title: 'One Love Movement', duration: '3:55', plays: '980K', album: 'Crown Pon Mi Head' },
      { title: 'Sound System God', duration: '4:12', plays: '760K', album: 'Yard Vibes Vol.1' },
    ],
    albums: [
      { title: 'Crown Pon Mi Head', year: 2023, tracks: 12 },
      { title: 'Yard Vibes Vol.1', year: 2022, tracks: 10 },
      { title: 'Elevation', year: 2021, tracks: 8 },
    ],
    upcomingShows: [
      { date: '2026-06-14', venue: 'Usain Bolt Tracks & Records', city: 'Kingston, JA' },
      { date: '2026-07-03', venue: 'O2 Arena', city: 'London, UK' },
      { date: '2026-08-22', venue: 'Barclays Center', city: 'New York, USA' },
    ],
  },
  {
    slug: 'empress-zara',
    name: 'Empress Zara',
    genre: 'Reggae',
    subGenre: 'Roots Reggae',
    origin: 'Trench Town, Jamaica',
    bio: "Empress Zara brings the timeless spirit of roots reggae into the modern era. Her powerful vocals and conscious lyrics have earned her a devoted international following and critical acclaim from reggae purists and new listeners alike.",
    longBio: "Growing up in the legendary Trench Town neighborhood of Kingston, Empress Zara absorbed the rich musical heritage that produced many of reggae's greatest artists. Her debut EP 'Natural Mystic Rising' announced her arrival as a major voice in roots reggae, and her subsequent albums have cemented her reputation as one of the genre's most important artists of her generation.",
    image: null,
    color: '#00ffcc',
    stats: { streams: '8M+', shows: '150+', albums: 2, awards: 5 },
    socials: { instagram: '#', twitter: '#', youtube: '#', spotify: '#' },
    tracks: [
      { title: 'Natural Mystic Rising', duration: '4:15', plays: '1.5M', album: 'Natural Mystic Rising EP' },
      { title: 'Zion Gates', duration: '3:58', plays: '1.2M', album: 'Earth & Fire' },
      { title: 'Empress Calling', duration: '4:33', plays: '890K', album: 'Earth & Fire' },
      { title: 'Roots & Culture', duration: '3:47', plays: '650K', album: 'Natural Mystic Rising EP' },
    ],
    albums: [
      { title: 'Earth & Fire', year: 2024, tracks: 11 },
      { title: 'Natural Mystic Rising EP', year: 2022, tracks: 6 },
    ],
    upcomingShows: [
      { date: '2026-06-28', venue: 'Reggae Sunsplash', city: 'Montego Bay, JA' },
      { date: '2026-09-12', venue: 'Rototom Sunsplash', city: 'Benicàssim, Spain' },
    ],
  },
  {
    slug: 'dj-yardie-flash',
    name: 'DJ Yardie Flash',
    genre: 'DJ / Selector',
    subGenre: 'Sound System',
    origin: 'Spanish Town, Jamaica',
    bio: "The most electrifying selector in the YardStyle sound system, DJ Yardie Flash commands dance floors across three continents. His mixing skills, rare dubplate collection, and crowd connection are unmatched in the dancehall circuit.",
    longBio: "DJ Yardie Flash began his career at age 15, cutting his teeth on the legendary sound system circuit of Spanish Town. His reputation for pulling the rarest dubs and reading the crowd with surgical precision earned him the position of lead selector for YardStyle Sound. He has clashed and triumphed against some of the world's greatest sound systems, earning respect from Kingston to Tokyo.",
    image: null,
    color: '#39ff14',
    stats: { streams: '5M+', shows: '350+', albums: 1, awards: 12 },
    socials: { instagram: '#', twitter: '#', youtube: '#', spotify: '#' },
    tracks: [
      { title: 'Clash Mix Vol.1 (Live)', duration: '45:00', plays: '500K', album: 'Sound Clashes' },
      { title: 'Dubplate Special 2024', duration: '32:00', plays: '380K', album: 'Dubplate Specials' },
    ],
    albums: [
      { title: 'Sound Clashes: Live Recordings', year: 2023, tracks: 5 },
    ],
    upcomingShows: [
      { date: '2026-07-19', venue: 'Dub Club LA', city: 'Los Angeles, USA' },
      { date: '2026-08-08', venue: 'Fabric', city: 'London, UK' },
      { date: '2026-10-04', venue: 'Oath', city: 'Tokyo, Japan' },
    ],
  },
  {
    slug: 'ras-marcus',
    name: 'Ras Marcus',
    genre: 'Reggae / Dub',
    subGenre: 'Dub Poetry',
    origin: 'Clarendon, Jamaica',
    bio: "Ras Marcus blends dub production mastery with spoken word poetry, creating immersive sonic journeys that honor Jamaica's musical traditions while pushing into experimental territory.",
    longBio: "Raised in the rural parish of Clarendon, Ras Marcus developed a deep connection to the land and its stories that permeates every track he produces. After studying audio engineering at the Caribbean Institute of Media and Communication, he returned to his roots to create music that speaks to the Jamaican experience in all its complexity.",
    image: null,
    color: '#d4af37',
    stats: { streams: '3.5M+', shows: '100+', albums: 4, awards: 3 },
    socials: { instagram: '#', twitter: '#', youtube: '#', spotify: '#' },
    tracks: [
      { title: 'Dub Philosophy', duration: '6:22', plays: '450K', album: 'Earthworks' },
      { title: 'Version Consciousness', duration: '5:48', plays: '320K', album: 'Earthworks' },
    ],
    albums: [
      { title: 'Earthworks', year: 2023, tracks: 9 },
      { title: 'Dub Sessions Vol.3', year: 2022, tracks: 7 },
      { title: 'Dub Sessions Vol.2', year: 2021, tracks: 7 },
      { title: 'Dub Sessions Vol.1', year: 2020, tracks: 8 },
    ],
    upcomingShows: [],
  },
  {
    slug: 'sista-nova',
    name: 'Sista Nova',
    genre: 'Afrobeats / Reggae',
    subGenre: 'Caribbean Fusion',
    origin: 'Montego Bay, Jamaica',
    bio: "Sista Nova is the sound of the Caribbean's global future — fusing Afrobeats rhythms with reggae soul and dancehall energy to create a genre-defying sound that's lighting up charts worldwide.",
    longBio: "Born in Montego Bay to Jamaican-Nigerian parents, Sista Nova grew up navigating multiple musical worlds. Her debut single 'Caribbean Queen' became a viral phenomenon, and her subsequent work has established her as one of the most exciting voices in Caribbean fusion music.",
    image: null,
    color: '#ff0077',
    stats: { streams: '6M+', shows: '80+', albums: 1, awards: 4 },
    socials: { instagram: '#', twitter: '#', youtube: '#', spotify: '#' },
    tracks: [
      { title: 'Caribbean Queen', duration: '3:28', plays: '2.8M', album: 'Nova Rising' },
      { title: 'Afro Yardie', duration: '3:55', plays: '1.9M', album: 'Nova Rising' },
      { title: 'Island Fire', duration: '4:02', plays: '890K', album: 'Nova Rising' },
    ],
    albums: [
      { title: 'Nova Rising', year: 2024, tracks: 13 },
    ],
    upcomingShows: [
      { date: '2026-06-21', venue: 'Afropunk', city: 'Brooklyn, USA' },
      { date: '2026-07-26', venue: 'WOMAD', city: 'Charlton Park, UK' },
    ],
  },
  {
    slug: 'selector-mighty',
    name: 'Selector Mighty',
    genre: 'DJ / Sound System',
    subGenre: 'Dancehall / Soca',
    origin: 'Kingston, Jamaica',
    bio: "Selector Mighty is the energy architect of YardStyle's live events, known for seamlessly blending dancehall, soca, and Afrobeats into explosive sets that keep crowds moving for hours.",
    longBio: "A Kingston native who grew up in the shadow of the famous Stone Love sound system, Selector Mighty learned the craft from the legends. His ability to blend genres and his instinctive understanding of crowd psychology have made him one of the most sought-after selectors in the Caribbean events circuit.",
    image: null,
    color: '#00ffcc',
    stats: { streams: '2M+', shows: '400+', albums: 0, awards: 6 },
    socials: { instagram: '#', twitter: '#', youtube: '#', spotify: '#' },
    tracks: [
      { title: 'Summer Fête Mix 2024', duration: '60:00', plays: '200K', album: 'Live Mixes' },
    ],
    albums: [],
    upcomingShows: [
      { date: '2026-07-12', venue: 'Notting Hill Carnival', city: 'London, UK' },
      { date: '2026-08-31', venue: 'Miami Carnival', city: 'Miami, USA' },
    ],
  },
]

export const releases = [
  {
    id: 1,
    title: 'Crown Pon Mi Head',
    artist: 'King Yardie',
    artistSlug: 'king-yardie',
    type: 'Album',
    year: 2023,
    genre: 'Dancehall',
    tracks: 12,
    label: 'YardStyle Entertainment',
    streaming: { spotify: '#', apple: '#', youtube: 'https://www.youtube.com/watch?v=Ko3Vd8MRnIc&list=PL6Z_Z01uENh7tTk83YzuLZuMZrKI7LmN6', tidal: '#' },
    featured: true,
  },
  {
    id: 2,
    title: 'Earth & Fire',
    artist: 'Empress Zara',
    artistSlug: 'empress-zara',
    type: 'Album',
    year: 2024,
    genre: 'Roots Reggae',
    tracks: 11,
    label: 'YardStyle Entertainment',
    streaming: { spotify: '#', apple: '#', youtube: '#', tidal: '#' },
    featured: true,
  },
  {
    id: 3,
    title: 'Nova Rising',
    artist: 'Sista Nova',
    artistSlug: 'sista-nova',
    type: 'Album',
    year: 2024,
    genre: 'Afrobeats / Reggae',
    tracks: 13,
    label: 'YardStyle Entertainment',
    streaming: { spotify: '#', apple: '#', youtube: '#', tidal: '#' },
    featured: true,
  },
  {
    id: 4,
    title: 'Caribbean Queen',
    artist: 'Sista Nova',
    artistSlug: 'sista-nova',
    type: 'Single',
    year: 2024,
    genre: 'Caribbean Fusion',
    tracks: 1,
    label: 'YardStyle Entertainment',
    streaming: { spotify: '#', apple: '#', youtube: '#', tidal: '#' },
    featured: false,
  },
  {
    id: 5,
    title: 'Earthworks',
    artist: 'Ras Marcus',
    artistSlug: 'ras-marcus',
    type: 'Album',
    year: 2023,
    genre: 'Dub / Reggae',
    tracks: 9,
    label: 'YardStyle Entertainment',
    streaming: { spotify: '#', apple: '#', youtube: '#', tidal: '#' },
    featured: false,
  },
  {
    id: 6,
    title: 'Yardie Anthem',
    artist: 'King Yardie',
    artistSlug: 'king-yardie',
    type: 'Single',
    year: 2024,
    genre: 'Dancehall',
    tracks: 1,
    label: 'YardStyle Entertainment',
    streaming: { spotify: '#', apple: '#', youtube: '#', tidal: '#' },
    featured: false,
  },
  {
    id: 7,
    title: 'Zion Gates',
    artist: 'Empress Zara',
    artistSlug: 'empress-zara',
    type: 'Single',
    year: 2024,
    genre: 'Roots Reggae',
    tracks: 1,
    label: 'YardStyle Entertainment',
    streaming: { spotify: '#', apple: '#', youtube: '#', tidal: '#' },
    featured: false,
  },
  {
    id: 8,
    title: 'Sound Clashes: Live Recordings',
    artist: 'DJ Yardie Flash',
    artistSlug: 'dj-yardie-flash',
    type: 'Live Album',
    year: 2023,
    genre: 'Sound System',
    tracks: 5,
    label: 'YardStyle Entertainment',
    streaming: { spotify: '#', apple: '#', youtube: '#', tidal: '#' },
    featured: false,
  },
]

export const events = [
  {
    id: 1,
    title: 'YardStyle Summer Clash 2026',
    date: '2026-07-05',
    time: '8:00 PM',
    venue: 'National Stadium',
    city: 'Kingston, Jamaica',
    type: 'Sound Clash',
    artists: ['King Yardie', 'DJ Yardie Flash', 'Selector Mighty'],
    tickets: '#',
    featured: true,
    description: 'The biggest sound clash of the year. Three world-class selectors battle it out in the home of dancehall.',
  },
  {
    id: 2,
    title: 'Notting Hill Carnival 2026',
    date: '2026-08-25',
    time: '10:00 AM',
    venue: 'Ladbroke Grove',
    city: 'London, UK',
    type: 'Festival',
    artists: ['King Yardie', 'Empress Zara', 'Selector Mighty'],
    tickets: '#',
    featured: true,
    description: 'YardStyle brings the full sound system experience to the world\'s greatest Caribbean street festival.',
  },
  {
    id: 3,
    title: 'Reggae Sunsplash 2026',
    date: '2026-06-28',
    time: '6:00 PM',
    venue: 'Catherine Hall Complex',
    city: 'Montego Bay, Jamaica',
    type: 'Festival',
    artists: ['Empress Zara', 'Ras Marcus'],
    tickets: '#',
    featured: true,
    description: 'Empress Zara headlines the reggae stage at the legendary Sunsplash festival.',
  },
  {
    id: 4,
    title: 'YSE London Showcase',
    date: '2026-09-18',
    time: '9:00 PM',
    venue: 'O2 Academy Brixton',
    city: 'London, UK',
    type: 'Concert',
    artists: ['King Yardie', 'Empress Zara', 'Sista Nova', 'DJ Yardie Flash'],
    tickets: '#',
    featured: false,
    description: 'Full YardStyle roster live in Brixton for an unforgettable night.',
  },
  {
    id: 5,
    title: 'Miami Carnival 2026',
    date: '2026-10-10',
    time: '12:00 PM',
    venue: 'Miami-Dade County Park',
    city: 'Miami, USA',
    type: 'Festival',
    artists: ['Sista Nova', 'Selector Mighty'],
    tickets: '#',
    featured: false,
    description: 'Sista Nova and Selector Mighty bring Caribbean vibes to South Florida.',
  },
  {
    id: 6,
    title: 'Tokyo Sound System Experience',
    date: '2026-10-04',
    time: '8:00 PM',
    venue: 'Oath',
    city: 'Tokyo, Japan',
    type: 'Club Night',
    artists: ['DJ Yardie Flash'],
    tickets: '#',
    featured: false,
    description: 'YardStyle Sound brings authentic Jamaican sound system culture to the heart of Tokyo.',
  },
]

export const soundPackages = [
  {
    id: 1,
    name: 'Yard Starter',
    tagline: 'Perfect for house parties & small events',
    priceRange: '$500 – $1,200',
    capacity: 'Up to 200 people',
    duration: 'Up to 6 hours',
    features: [
      '4x 15" Sub Bass Speakers',
      '4x Mid-Range Cabinets',
      '2x High-Frequency Horns',
      'Professional Amplification',
      'DJ Booth Setup',
      'Basic Lighting Package',
      'Professional Selector',
      'Setup & Breakdown Included',
    ],
    popular: false,
    color: 'rgba(255,255,255,0.05)',
  },
  {
    id: 2,
    name: 'Sound System Royale',
    tagline: 'The full YardStyle experience',
    priceRange: '$2,500 – $5,000',
    capacity: 'Up to 1,000 people',
    duration: 'Up to 10 hours',
    features: [
      '12x 18" Heavy Duty Sub Bass',
      '8x Mid-Range Stack Cabinets',
      '6x High-Frequency Arrays',
      'Custom YardStyle Speaker Walls',
      'Professional DJ Booth & CDJs',
      'Full Lighting Rig (LED + Lasers)',
      'Lead Selector (DJ Yardie Flash)',
      'Sound Engineer On-Site',
      'Custom Dubplate Selection',
      'Setup 6 Hours Before Event',
      'Marketing Materials Included',
    ],
    popular: true,
    color: 'rgba(212,175,55,0.06)',
  },
  {
    id: 3,
    name: 'Festival Command',
    tagline: 'Massive scale. Uncompromising power.',
    priceRange: '$8,000+',
    capacity: '5,000+ people',
    duration: 'Full Event Coverage',
    features: [
      '24x 21" Subwoofer Array',
      '16x Mid-Range Tower Stacks',
      '12x High-Frequency Line Arrays',
      'Delay Speaker Systems',
      'Full Stage Production',
      'Concert-Grade Amplification',
      'Professional Sound Engineer Team',
      'Full Lighting Production',
      'LED Video Walls',
      'Multiple DJ / Selector Team',
      'VIP Artist Management',
      'Event Planning Consultation',
      'Pre/Post Event Support',
    ],
    popular: false,
    color: 'rgba(255,255,255,0.05)',
  },
]

export const stats = [
  { label: 'Artists Managed', value: '15+' },
  { label: 'Events Powered', value: '500+' },
  { label: 'Countries Reached', value: '30+' },
  { label: 'Streams Worldwide', value: '50M+' },
]

export const genres = ['All', 'Dancehall', 'Reggae', 'Roots Reggae', 'Dub', 'Afrobeats', 'Caribbean Fusion', 'Sound System']
export const releaseTypes = ['All', 'Album', 'Single', 'Live Album', 'EP']
